## Larger topology example: GEANT (Topology Zoo)
topology: data/topozoo/Geant2012.graphml
topology_name: geant
out_dir: out/geant
seed: 8

directed: false
# Capacity-aware routing: flows prefer higher-capacity links.
edge_weight_attr: inv_capacity

flow_count: 500000 # Max limit
flow_model: size_dist
allow_self_flows: false
